class VerificationService:
    """
    Verifies the markdown content generated by the LLM.
    """
    def __init__(self):
        pass

    def verify_markdown(self, markdown_content):
        """
        Perform basic verification on generated markdown.

        :param markdown_content: Generated markdown text
        :return: Verified markdown or raises ValueError
        """
        if not isinstance(markdown_content, str):
            markdown_content = str(markdown_content)

        if not markdown_content:
            raise ValueError("No content generated")

        if len(markdown_content) < 10:  # Minimum content length
            raise ValueError("Generated content is too short")

        return markdown_content